version: '3.8'

services:
  abs-meta:
    build: .
    ports:
      - "8723:8723"
    volumes:
      - cache_data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=8723
    restart: unless-stopped    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8723/health"]
      interval: 600s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  cache_data:
